/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.bancopresentaciones;


import banco.banconegocio.controlador.ControlNegocio;
import banco.banconegocio.controlador.IControlNegocio;
import banco.banconegocio.excepciones.NegocioException;
import banco.bancopresentacion.control.ControlPresentacion;
import banco.bancopresentacion.utilities.FondoImagen;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author molin
 */
public class Registro extends javax.swing.JFrame {
    
    IControlNegocio control=new ControlNegocio();
    ControlPresentacion controlP=new ControlPresentacion();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setLogo();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbl_apP = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        lbl_apM = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        lbl_fecha = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbl_cp = new javax.swing.JLabel();
        txt_cp = new javax.swing.JTextField();
        lbl_calle = new javax.swing.JLabel();
        txt_calle = new javax.swing.JTextField();
        lbl_colonia = new javax.swing.JLabel();
        txt_colonia = new javax.swing.JTextField();
        lbl_num = new javax.swing.JLabel();
        txt_numeroDireccion = new javax.swing.JTextField();
        ButtonRegreso = new javax.swing.JButton();
        icono1 = new javax.swing.JLabel();
        ButtonAceptar = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre:");
        jPanel1.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 250, 30));

        lbl_apP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_apP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apP.setText("Apellido Paterno:");
        jPanel1.add(lbl_apP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 250, 30));

        lbl_apM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_apM.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apM.setText("Apellido Materno:");
        jPanel1.add(lbl_apM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, 30));

        lbl_fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha.setText("Fecha de nacimiento:");
        jPanel1.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 250, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lbl_cp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cp.setText("Codigo Postal:");
        jPanel1.add(lbl_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        txt_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpActionPerformed(evt);
            }
        });
        txt_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cpKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 250, 30));

        lbl_calle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_calle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_calle.setText("Calle:");
        jPanel1.add(lbl_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 10));
        jPanel1.add(txt_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 250, 30));

        lbl_colonia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_colonia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_colonia.setText("Colonia:");
        jPanel1.add(lbl_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 20));
        jPanel1.add(txt_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 250, 30));

        lbl_num.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_num.setForeground(new java.awt.Color(255, 255, 255));
        lbl_num.setText("Número exterior:");
        jPanel1.add(lbl_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, 10));
        jPanel1.add(txt_numeroDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 250, 30));

        ButtonRegreso.setBackground(new java.awt.Color(14, 33, 110));
        ButtonRegreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonRegreso.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        icono1.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\Downloads\\ProyectoFinal_Banco\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\registrate-removebg-preview (1) (1).png")); // NOI18N
        jPanel1.add(icono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 140, 110));

        ButtonAceptar.setBackground(new java.awt.Color(14, 33, 110));
        ButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAceptar.setText("Aceptar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 140, 40));

        fondo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\Downloads\\ProyectoFinal_Banco\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\fondo4.png")); // NOI18N
        jPanel1.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 360, 470));

        fondo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\Downloads\\ProyectoFinal_Banco\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\fondo1.png")); // NOI18N
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
        // TODO add your handling code here:
         // Obtener los datos ingresados por el usuario
        int cant=validarCamposVacios();
        if(cant>0){
            JOptionPane.showMessageDialog(this, "Dejo vacios "+cant+" espacios que son obligatorios.\n"
                    + "Por favor ingrese la informacion de los campos resaltados en rojo");
        }else if(validarInformacion()>0){
            JOptionPane.showMessageDialog(this, """
                                                Ingreso informacion invalida.
                                                Por favor corrija la informacion en los campos resaltados en rojo""");
        }else{
            String[] datosCliente = {txtNombre.getText(),
                txtApellidoP.getText(),
                txtApellidoM.getText(),
                txtFechaNacimiento.getText()};

            String[] datosDireccion = {txt_calle.getText(),
                txt_colonia.getText(),
                txt_cp.getText(),
                txt_numeroDireccion.getText()
            };
            try {
                int id=this.agregarCliente(datosCliente, datosDireccion);
                DlgUsuario dlg=new DlgUsuario(this, true,id);
                this.dispose();
                controlP.despliegaPrincipal();
            } catch (NegocioException e) {
                System.out.println(e.getCause());
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    private void txt_cpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cpKeyTyped
        // TODO add your handling code here:
        if(txt_cp.getText().length()==5)
            evt.consume();
    }//GEN-LAST:event_txt_cpKeyTyped

    private void txt_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpActionPerformed

    private void ButtonRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresoActionPerformed
        // TODO add your handling code here:
        controlP.despliegaInicio();
        this.dispose();
    }//GEN-LAST:event_ButtonRegresoActionPerformed

    private int agregarCliente(String[] datos_cliente, String[] datos_direccion)
            throws NegocioException {
        int codigo_direccion = this.control.agregarDireccionCliente(datos_direccion[0], datos_direccion[1], datos_direccion[2], datos_direccion[3]);
        int idCliente=this.control.insertarCliente(datos_cliente[0], datos_cliente[1], datos_cliente[2], datos_cliente[3], codigo_direccion);
        return idCliente;
    }

    private int validarCamposVacios(){
        JTextField[] componentes = {txtNombre, txtApellidoP, txtFechaNacimiento,txt_calle, txt_cp};
        JLabel[] labels={lbl_nombre,lbl_apP,lbl_fecha,lbl_calle,lbl_cp};
        int contador=0;
        for (int i = 0; i < 5; i++) {
            if(componentes[i].getText().isBlank()){
                labels[i].setForeground(Color.red);
                contador++;
            }else
                labels[i].setForeground(Color.white);
        }
        return contador;
    }

    private int validarInformacion(){
        int contador=validarFecha();
        String[] campos = {txtNombre.getText(), txtApellidoP.getText(), txtApellidoM.getText(), 
            txt_calle.getText(), txt_colonia.getText()};
        JLabel[] labels={lbl_nombre,lbl_apP,lbl_apM,lbl_calle,lbl_colonia};
        Pattern patron = Pattern.compile("^[a-zA-Z]+$");
        Matcher matcher;
       
        for (int i = 0; i < 5; i++) {
            matcher = patron.matcher(campos[i]);
            if (!matcher.matches()) {
                labels[i].setForeground(Color.red);
                contador++;
            }else
                labels[i].setForeground(Color.white);
        }
        return contador;
    }
    
    private int validarFecha(){
        if(!Pattern.matches("^(?!2024)(?:19|20)\\d{2}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])$", txtFechaNacimiento.getText())){
            lbl_fecha.setForeground(Color.red);
            return 1;
        }else
            lbl_fecha.setForeground(Color.white);
        return 0;
    }
    
    private void setLogo(){
        try{
            File file =new File("Imagenes/icono5.png");
            BufferedImage imagen=ImageIO.read(file);
            FondoImagen fondo= new FondoImagen(imagen);
            ButtonRegreso.setBorder(fondo);
        }catch(IOException e){
            e.printStackTrace();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonRegreso;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel icono1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_apM;
    private javax.swing.JLabel lbl_apP;
    private javax.swing.JLabel lbl_calle;
    private javax.swing.JLabel lbl_colonia;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_num;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txt_calle;
    private javax.swing.JTextField txt_colonia;
    private javax.swing.JTextField txt_cp;
    private javax.swing.JTextField txt_numeroDireccion;
    // End of variables declaration//GEN-END:variables
}
