
package banco.bancopresentacion;

import banco.bancopresentacion.control.ControlPresentacion;

/**
 *
 * @author molin
 */
public class Inicial extends javax.swing.JFrame {
    private ControlPresentacion control=new ControlPresentacion();;
    /**
     * Creates new form Principal
     */
    public Inicial() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ButtonRetiro = new javax.swing.JButton();
        ButtonIniciarSesion1 = new javax.swing.JButton();
        ButtonRegistrarse1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 630));
        setMinimumSize(new java.awt.Dimension(360, 630));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonRetiro.setBackground(new java.awt.Color(14, 33, 110));
        ButtonRetiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonRetiro.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRetiro.setText("Retiro Sin Cuenta");
        ButtonRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetiroActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 160, 40));

        ButtonIniciarSesion1.setBackground(new java.awt.Color(14, 33, 110));
        ButtonIniciarSesion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonIniciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonIniciarSesion1.setText("Iniciar Sesión");
        ButtonIniciarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniciarSesion1ActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 160, 40));

        ButtonRegistrarse1.setBackground(new java.awt.Color(14, 33, 110));
        ButtonRegistrarse1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonRegistrarse1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegistrarse1.setText("Registrarse");
        ButtonRegistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistrarse1ActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\luiis\\Dropbox\\PC\\Documents\\proyectoFinal-Banco-BDA\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\fondo2.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(360, 460));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 400, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetiroActionPerformed
        // TODO add your handling code here:
        control.despliegaRetiroSinCuenta();
        this.dispose();
    }//GEN-LAST:event_ButtonRetiroActionPerformed

    private void ButtonIniciarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniciarSesion1ActionPerformed
        // TODO add your handling code here:
        control.despliegaLogin();
        this.dispose();
    }//GEN-LAST:event_ButtonIniciarSesion1ActionPerformed

    private void ButtonRegistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistrarse1ActionPerformed
        // TODO add your handling code here:
        control.despliegaRegistro();
        this.dispose();
    }//GEN-LAST:event_ButtonRegistrarse1ActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIniciarSesion1;
    private javax.swing.JButton ButtonRegistrarse1;
    private javax.swing.JButton ButtonRetiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
