/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.bancopresentacion;

import banco.banconegocio.controlador.ControlNegocio;
import banco.banconegocio.controlador.IControlNegocio;
import banco.banconegocio.excepciones.NegocioException;
import banco.bancopresentacion.control.ControlPresentacion;
import javax.swing.JOptionPane;

/**
 *
 * @author luiis
 */
public class PerfilUsuario extends javax.swing.JFrame {
    IControlNegocio control=new ControlNegocio();
    ControlPresentacion controlP= new ControlPresentacion();
    /*
    indicador para verificar si se dio click en el boton editar
    la primera vez que se de click el indicador cambiara a true, lo que 
    significa que se habilitara la opcion de editar la informacion del cliente,
    la segunda vez que se de click sera para confirmar los cambios y 
    el indicador volvera a false
    */
    private boolean flag;
    
    /**
     * Creates new form PerfilUsuario
     */
    public PerfilUsuario() {
        initComponents();
        this.setVisible(true);
        flag=false;
        this.habilitarEdicion(flag,"editar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_editar = new javax.swing.JButton();
        lbl_atras = new javax.swing.JLabel();
        txt_colonia = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        txt_cp = new javax.swing.JTextField();
        txt_calle = new javax.swing.JTextField();
        txt_apM = new javax.swing.JTextField();
        txt_fechaN = new javax.swing.JTextField();
        txt_apP = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 630));
        setMinimumSize(new java.awt.Dimension(360, 630));
        setPreferredSize(new java.awt.Dimension(360, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(0, 0, 51));
        btn_editar.setText("editar");
        btn_editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 100, 40));

        lbl_atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_atrasMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 40));

        txt_colonia.setBackground(new java.awt.Color(255, 255, 255));
        txt_colonia.setBorder(null);
        txt_colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_coloniaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 130, 30));

        txt_numero.setBackground(new java.awt.Color(255, 255, 255));
        txt_numero.setBorder(null);
        getContentPane().add(txt_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 130, 30));

        txt_cp.setBackground(new java.awt.Color(255, 255, 255));
        txt_cp.setBorder(null);
        getContentPane().add(txt_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 130, 30));

        txt_calle.setBackground(new java.awt.Color(255, 255, 255));
        txt_calle.setBorder(null);
        getContentPane().add(txt_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 30));

        txt_apM.setBackground(new java.awt.Color(255, 255, 255));
        txt_apM.setBorder(null);
        getContentPane().add(txt_apM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 250, 30));

        txt_fechaN.setBackground(new java.awt.Color(255, 255, 255));
        txt_fechaN.setToolTipText("");
        txt_fechaN.setBorder(null);
        getContentPane().add(txt_fechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 250, 30));

        txt_apP.setBackground(new java.awt.Color(255, 255, 255));
        txt_apP.setBorder(null);
        getContentPane().add(txt_apP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 250, 30));

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 250, 30));

        fondo.setForeground(new java.awt.Color(0, 0, 51));
        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\luiis\\Dropbox\\PC\\Documents\\proyectoFinal-Banco-BDA\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\fondo-miPerfil.png")); // NOI18N
        fondo.setPreferredSize(new java.awt.Dimension(360, 630));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void habilitarEdicion(boolean indicador,String txtBoton){
        txt_nombre.setEditable(indicador);
        txt_apP.setEditable(indicador);
        txt_apM.setEditable(indicador);
        txt_calle.setEditable(indicador);
        txt_colonia.setEditable(indicador);
        txt_cp.setEditable(indicador);
        txt_numero.setEditable(indicador);
        btn_editar.setText(txtBoton);
    }
    
    private void lbl_atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_atrasMouseClicked
        // TODO add your handling code here:
        controlP.despliegaPrincipal();
        this.dispose();
    }//GEN-LAST:event_lbl_atrasMouseClicked

    private void txt_coloniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_coloniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_coloniaActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        String nombre=txt_nombre.getText();
        String apellidoP=txt_apP.getText();
        String apellidoM=txt_apM.getText();
        String calle=txt_calle.getText();
        String colonia=txt_colonia.getText();
        String cp=txt_cp.getText();
        String numero=txt_numero.getText();
        
        try {
            int[] ids=controlP.obtenIds();
            this.actualizarCliente(ids[0], nombre, apellidoP, apellidoM, calle, ids[1]);
            this.actualizarDireccion(ids[1], calle, colonia, cp, numero);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void actualizarCliente(int idCliente, String nombre, String apellidoP, String apellidoM,
            String fechaNac, int idDireccion)throws NegocioException{
        if(nombre.isBlank())
            nombre=null;
        if(apellidoP.isBlank())
            apellidoP=null;
        if(apellidoM.isBlank())
            apellidoM=null;
        if(fechaNac.isBlank())
            fechaNac=null;
        control.actualizarCliente(idCliente, nombre, apellidoP, apellidoM, fechaNac, idDireccion);
    }
    
    private void actualizarDireccion(int idDireccion, String calle, String colonia, String codigoPostal,
            String numero)throws NegocioException{
        if(calle.isBlank())
            calle=null;
        if(colonia.isBlank())
            colonia=null;
        if(codigoPostal.isBlank())
            codigoPostal=null;
        if(numero.isBlank())
            numero=null;
        control.actualizarDireccionCliente(idDireccion, calle, colonia, codigoPostal, numero);
    }

    private void setInfo(){
        control.
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lbl_atras;
    private javax.swing.JTextField txt_apM;
    private javax.swing.JTextField txt_apP;
    private javax.swing.JTextField txt_calle;
    private javax.swing.JTextField txt_colonia;
    private javax.swing.JTextField txt_cp;
    private javax.swing.JTextField txt_fechaN;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numero;
    // End of variables declaration//GEN-END:variables
}
