/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.bancopresentacion;


import banco.banconegocio.controlador.ControlNegocio;
import banco.banconegocio.controlador.IControlNegocio;
import banco.banconegocio.excepciones.NegocioException;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author molin
 */
public class Registro extends javax.swing.JFrame {
    
    IControlNegocio control=new ControlNegocio();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbl_apP = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        lbl_apM = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        lbl_fecha = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbl_cp = new javax.swing.JLabel();
        txt_cp = new javax.swing.JTextField();
        lbl_calle = new javax.swing.JLabel();
        txt_calle = new javax.swing.JTextField();
        lbl_colonia = new javax.swing.JLabel();
        txt_colonia = new javax.swing.JTextField();
        lbl_num = new javax.swing.JLabel();
        txt_numeroDireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ButtonAceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre:");
        jPanel1.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 250, -1));

        lbl_apP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_apP.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apP.setText("Apellido Paterno:");
        jPanel1.add(lbl_apP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 250, -1));

        lbl_apM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_apM.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apM.setText("Apellido Materno:");
        jPanel1.add(lbl_apM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 250, -1));

        lbl_fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha.setText("Fecha de nacimiento:");
        jPanel1.add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 250, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        lbl_cp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cp.setText("Codigo Postal:");
        jPanel1.add(lbl_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        txt_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cpKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 250, 20));

        lbl_calle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_calle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_calle.setText("Calle:");
        jPanel1.add(lbl_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 10));
        jPanel1.add(txt_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 250, 20));

        lbl_colonia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_colonia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_colonia.setText("Colonia:");
        jPanel1.add(lbl_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, 10));
        jPanel1.add(txt_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 250, 20));

        lbl_num.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_num.setForeground(new java.awt.Color(255, 255, 255));
        lbl_num.setText("Número exterior:");
        jPanel1.add(lbl_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, 10));
        jPanel1.add(txt_numeroDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 250, 20));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 140, 110));

        ButtonAceptar.setBackground(new java.awt.Color(14, 33, 110));
        ButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAceptar.setText("Aceptar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 130, 40));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 360, 470));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
        // TODO add your handling code here:
         // Obtener los datos ingresados por el usuario
        int cant=validarCamposVacios();
        if(cant>0){
            JOptionPane.showMessageDialog(this, "Dejo vacios "+cant+" espacios que son obligatorios.\n"
                    + "Por favor ingrese la informacion de los campos resaltados en rojo");
        }else if(validarInformacion()>0){
            JOptionPane.showMessageDialog(this, """
                                                Ingreso informacion invalida.
                                                Por favor corrija la informacion en los campos resaltados en rojo""");
        }else{
            String[] datosCliente = {txtNombre.getText(),
                txtApellidoP.getText(),
                txtApellidoM.getText(),
                txtFechaNacimiento.getText()};

            String[] datosDireccion = {txt_calle.getText(),
                txt_colonia.getText(),
                txt_cp.getText(),
                txt_numeroDireccion.getText()
            };
            try {
                this.agregarCliente(datosCliente, datosDireccion);
                JOptionPane.showMessageDialog(this, "se agrego correctamente al cliente");
            } catch (NegocioException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    private void txt_cpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cpKeyTyped
        // TODO add your handling code here:
        if(txt_cp.getText().length()==5)
            evt.consume();
    }//GEN-LAST:event_txt_cpKeyTyped

    private void agregarCliente(String[] datos_cliente, String[] datos_direccion)
            throws NegocioException {
        int codigo_direccion = this.control.agregarDireccionCliente(datos_direccion[0], datos_direccion[1], datos_direccion[2], datos_direccion[3]);
        this.control.insertarCliente(datos_cliente[0], datos_cliente[1], datos_cliente[2], datos_cliente[3], codigo_direccion);
    }

    private int validarCamposVacios(){
        JTextField[] componentes = {txtNombre, txtApellidoP, txtFechaNacimiento,txt_calle, txt_cp};
        JLabel[] labels={lbl_nombre,lbl_apP,lbl_fecha,lbl_calle,lbl_cp};
        int contador=0;
        for (int i = 0; i < 5; i++) {
            if(componentes[i].getText().isBlank()){
                labels[i].setForeground(Color.red);
                contador++;
            }else
                labels[i].setForeground(Color.white);
        }
        return contador;
    }

    private int validarInformacion(){
        int contador=validarFecha();
        String[] campos = {txtNombre.getText(), txtApellidoP.getText(), txtApellidoM.getText(), 
            txt_calle.getText(), txt_colonia.getText()};
        JLabel[] labels={lbl_nombre,lbl_apP,lbl_apM,lbl_calle,lbl_colonia};
        Pattern patron = Pattern.compile("^[a-zA-Z]+$");
        Matcher matcher;
       
        for (int i = 0; i < 5; i++) {
            matcher = patron.matcher(campos[i]);
            if (!matcher.matches()) {
                labels[i].setForeground(Color.red);
                contador++;
            }else
                labels[i].setForeground(Color.white);
        }
        return contador;
    }
    
    private int validarFecha(){
        if(!Pattern.matches("^(?!2024)(?:19|20)\\d{2}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])$", txtFechaNacimiento.getText())){
            lbl_fecha.setForeground(Color.red);
            return 1;
        }else
            lbl_fecha.setForeground(Color.white);
        return 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_apM;
    private javax.swing.JLabel lbl_apP;
    private javax.swing.JLabel lbl_calle;
    private javax.swing.JLabel lbl_colonia;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_num;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txt_calle;
    private javax.swing.JTextField txt_colonia;
    private javax.swing.JTextField txt_cp;
    private javax.swing.JTextField txt_numeroDireccion;
    // End of variables declaration//GEN-END:variables
}
