/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.bancopresentacion;

import banco.bancodominio.Retiro_sin_cuenta;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author molin
 */
public class Retiro_Sin_Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Retiro_Sin_Cuenta
     * @param folio
     * @param contrasena
     */
    public Retiro_Sin_Cuenta(int folio, String contrasena) {
        initComponents(); // Inicializar componentes gráficos
        txtFolio.setText(String.valueOf(folio)); // Establecer el folio en el campo txtFolio
        txtContra.setText(contrasena); // Establecer la contraseña en el campo txtContra

    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFolio = new javax.swing.JTextField();
        ButtonAceptar = new javax.swing.JButton();
        LabelCuenta = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        icono = new javax.swing.JButton();
        txtContra = new javax.swing.JTextField();
        LabelContra = new javax.swing.JLabel();
        LabelFolio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 640));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFolio.setEditable(false);
        txtFolio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolioActionPerformed(evt);
            }
        });
        jPanel1.add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 150, 30));

        ButtonAceptar.setBackground(new java.awt.Color(19, 48, 100));
        ButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAceptar.setText("Aceptar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 130, 40));

        LabelCuenta.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LabelCuenta.setForeground(new java.awt.Color(255, 255, 255));
        LabelCuenta.setText("Cuenta:");
        jPanel1.add(LabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 220, 30));

        icono.setBackground(new java.awt.Color(170, 193, 234));
        icono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        icono.setForeground(new java.awt.Color(255, 255, 255));
        icono.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\Downloads\\ProyectoFinal_Banco\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\icono5 (1).png")); // NOI18N
        icono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconoActionPerformed(evt);
            }
        });
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 40));

        txtContra.setEditable(false);
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        jPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 170, 30));

        LabelContra.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LabelContra.setForeground(new java.awt.Color(255, 255, 255));
        LabelContra.setText("Contraseña:");
        jPanel1.add(LabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        LabelFolio.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LabelFolio.setForeground(new java.awt.Color(255, 255, 255));
        LabelFolio.setText("Folio:");
        jPanel1.add(LabelFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\Downloads\\ProyectoFinal_Banco\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\fondo4.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\Downloads\\ProyectoFinal_Banco\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\icono_3.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 70, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\Downloads\\ProyectoFinal_Banco\\netbeans\\bancoPresentacion\\src\\main\\java\\banco\\bancopresentacion\\Imagenes\\fondo1.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolioActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_txtFolioActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
        // TODO add your handling code here:
        // Obtener los datos ingresados por el usuario
    
        
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void iconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconoActionPerformed
        // TODO add your handling code here:
        Principal regresar = new Principal();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_iconoActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retiro_Sin_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retiro_Sin_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retiro_Sin_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retiro_Sin_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
          
                
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JLabel LabelContra;
    private javax.swing.JLabel LabelCuenta;
    private javax.swing.JLabel LabelFolio;
    private javax.swing.JButton icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtFolio;
    // End of variables declaration//GEN-END:variables
}
